build:
	g++ -o ./main ./main.cpp ./drawing.cpp ./globaldata.cpp -lGL -lGLU -lglut -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -O3
build_debug:
	g++ -g -o ./main ./main.cpp ./drawing.cpp ./globaldata.cpp -lGL -lGLU -lglut -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -O3
run:
	./main
